db:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  username: root
  password: root
  database: bank
kafka:
  group: accountConsumer
  hostname: localhost:9092
  username: username
  password: password
